language: cpp

#cache:
#    ccache: true
#    directories:
#        - $HOME/.cache/sde

env:
    - arch=x86_64  subset=avx512

os:
    - linux

compiler:
    - clang

# The following gives us Ubuntu 14.04 LTS instead of 12.04 LTS
sudo: required
dist: trusty
#group: deprecated-2017Q2

install:
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y &&
      wget -O - http://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add - &&
      sudo tee /etc/apt/sources.list.d/llvm.list <<< "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-4.0 main" &&
      sudo apt-get update -q &&
      sudo apt-get install clang-4.0 libstdc++-6-dev -y &&
      export CXX=clang++-4.0 CC=clang-4.0

before_script:
    # ptrace_scope=0 is required on Ubuntu for SDE to work
    - if test "$TRAVIS_OS_NAME" = "linux"; then
        echo 0 | sudo tee /proc/sys/kernel/yama/ptrace_scope;
      fi
    - $CXX --version
    - cmake --version
    - export dashboard_model=Experimental
    - export build_type=Release
    - export NUMBER_OF_PROCESSORS=2

script:
    - ctest -VV -S scripts/test.cmake
